### ISSUE TITLE
VM Stoppage: multiple options

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/VMDIRAC#17]
As agreed with point 1.2 of http://indico.cern.ch/getFile.py/access?sessionId=6&resId=0&materialId=1&confId=238601:

It has to be possible to select between 2 different stoppage algorithms: Time-driven and Never. There should be the possibility to switch from one to the other based on the targeted cloud.
- Time-driven: the VM will shutdown after a (configurable) amount of time (JobAgent cycles) after which no jobs are matched.
- Never: the VM never shutdowns. 

Paramount to both is the Site-driven: if the site(cloud) will signal the VM to shutdown, we must be ready to oblige.

Considerations made in https://github.com/DIRACGrid/VMDIRAC/issues/16 also apply here.

**Comment by vmendez** [comment]
The initiall approach is to stop the VMs when:
policy 1) no more jobs in the queue and VM margin halt parameter reached (currently implemented)
policy 2) never
regarding the time-driven we will consider this policy once the WLCG has define an implement end-point constrain to this specification

**Comment by fstagni** [comment]
Hi Victor, 
do not forget about
"Paramount to both is the Site-driven: if the site(cloud) will signal the VM to shutdown, we must be ready to oblige."

Consider what is written at the end of
https://twiki.cern.ch/twiki/bin/view/LCG/WMTEGEnvironmentVariables
I think the VMMonitorAgent should be capable of shutting down the machine based on the proposed approach.

**Comment by fstagni** [comment]
HI Victor,
in the comment of PR40, it is written:

TODO: The particular HEPiX method to ask VMs to shootdown from the IaaS site provider site (requirement to be specified by HEPiX)

where are you with this topic?

**Comment by vmendez** [comment]
I have put it in other issue #37 because I don't like to develop external
system requirements specifications without any use case of such external
system to consider the design ("the evil is in the datails") and also to
test it previouslly to PR to integration. I would said that this testing
environment can be easily available at IBEX, can you ask at CERN IBEX,
please ? At PIC we would cosider to install a NFS for such "per site
folder" on the following weeks.
Could you close this #17, please ?

2013/5/10 fstagni notifications@github.com

> HI Victor,
> in the comment of PR40, it is written:
> 
> TODO: The particular HEPiX method to ask VMs to shootdown from the IaaS
> site provider site (requirement to be specified by HEPiX)
> 
> where are you with this topic?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DIRACGrid/VMDIRAC/issues/17#issuecomment-17715819
> .

## 

Víctor Méndez Muñoz
LHCb Tier1 Contact
Port d'Informació Científica (PIC)
Tel: +34935813772   Web: http://www.pic.es

PIC is maintained through a collaboration agreement between CIEMAT
(Ministerio de Ciencia e Innovación),
ECO (Generalitat de Catalunya), Universitat Autònoma de Barcelona and IFAE

---

IFAE provides the e-mail service used by PIC and requires this notice:
Avis - Aviso - Legal Notice:  http://www.ifae.es/legal.html
