### ISSUE TITLE
Proposal: Modify the VMDIRAC configuration structure

### ISSUE THREAD

**Issue by xianghuzhao** [DIRACGrid/VMDIRAC#91]
The goal for this proposal is to simplify the work for the administrator.
## `VirtualMachineScheduler` configuration

Do not need to set SubmitPools with runningpod names in `VirtualMachineScheduler` configuration. So the administrator does not need to write anything in the `Systems -> WorkloadManagement -> Production -> Agents -> VirturlMachineScheduler`.

The `VirtualMachineScheduler` can loop over all the allowed sites and see whether it is a cloud site.
Just find the "CloudEndpoint" section and check the "cloudDriver" config to see whether this is a good cloud endpoint.
## `Sites` configuration

Move some of the VirtualMachine configurations to the Sites section. The purpose is to keep the consistency to cluster and grid sites configuration.

This is the proposed structure:

```
Sites
    CLOUD.IHEP.cn
        CloudEndpoint = openstack.ihep.ac.cn, opennebula.ihep.ac.cn
        CloudEndpoints
            OwnerGroup = cloud_group
            cvmfs_http_proxy = DIRECT
            openstack.ihep.ac.cn
                cloudDriver = nova-1.1
                URI = http://...
                auth = userpasswd
                maxInstances = 20
                Setup = BES_Production
                Queues
                    SL6-BOSS
                        bootImageName = sl65-bes
                        Flavor = m1.small
                        Context = ssh-standard
                        vmPolicy = elastic
                        vmStopPolicy = elastic
                        maxEndpointInstances = 15
                        priority = 1
                        VO = bes
                        CPUTime = 86400
                        Platform = Linux_x86_64_glibc-2.12
                        architecture = x86_64
                        OS = ScientificSL_Carbon_6.5
                    SL5-CEPC
                        bootImageName = sl5-cepc
                        Flavor = m1.medium
                        Context = cloudInit-standard
                        vmPolicy = static
                        vmStopPolicy = never
                        maxEndpointInstances = 10
                        priority = 3
                        VO = cepc
                        ...
            opennebula.ihep.ac.cn
                cloudDriver = rocci-1.1
                URI = http://...
                ...
VirtualMachines
    Contexts
        cloudinit-standard
            ContextMethod = cloudinit
            vmDiracContextURL = ...
            ...
        ssh-standard
            ContextMethod = ssh
            vmDiracContextURL = ...
            ...
```
- `CloudEndpoint` is like the CE in cluster and grid sites. CloudEndpoint configurations are moved to specified endpoint.
- `Queues` here include image, contextualization, priority, requirements, etc.
  Requirements could be put any place under the site configuration. The scope for the requirement depends on where it is written.
- `maxInstances` can be set under endpoint and image, like what VMDIRAC is doing now.
  The `maxInstances` under endpoint can control the total instance number on this endpoint, including all images.
  The `maxInstances` under image will control the instance related to the image.
- What is your opinion about this configuration structure?
## Image management

The above configuration does not include `Images` part in the `VirtualMachines` section. All the image properties are put under `Sites` section.
What about only put an image ID under the queue section and put all the image information seperately under `VirtualMachines` section for the future image management system?

**Comment by vmendez** [comment]
SubmitPool is needed to setup multi community DIRAC services. (different submitPools are asigned to separated communiti VOs)
The "The VirtualMachineScheduler can loop over all the allowed sites " will not work in multiple communities DIRAC services without some intelligence, like the sumbitPool solution.

The way to configure at Systems -> WorkloadManagement -> Production -> Agents -> VirturlMachineScheduler is equivalent ot other computing resources in DIRAC, and to put a line there it is not much work to admins.

It is necesary to separate between site configuration and image contextualization, for your particulary case it is probably not necesary becasue you have a singel comunity instance with not to much ocurrences site-image
At the same time it is necessary to have RunningPod for two main reasons:
1) Running requiremnts could affect to several cloud end points
2) Accounting 

It would be highly interesting to implement the posibility of having several images for a running pod, instead of only one of the current version, This would ease admins life.

If you want to move cloud endpoints info to sites, this is a sensible proposal, although I would prefer to have all the VM setup together, but it is not a design issue and it is possible if you want to.

**Comment by vmendez** [comment]
@njutiger 

What do you think to my proposal of the last month, what updates are you thinking to implement?

**Comment by atsareg** [comment]
Done in v2
